DEBUG    urllib3.connectionpool:connectionpool.py:206 Starting new HTTP connection (1): 47.97.206.151:8883
DEBUG    urllib3.connectionpool:connectionpool.py:396 http://47.97.206.151:8883 "POST /api/v1/login HTTP/1.1" 200 439
DEBUG    root:Log.py:75 [DEBUG2020-05-13 12-17-20]登录成功token为:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEwMDMzNDYsIkxvZ2luVmVyaWZ5IjoxLCJleHAiOjE1ODkzODY2NDF9.MaGRoLJqT2XGJSF9uM2RW8Suu2kqpMCHwaYdO2oPVtA
DEBUG    urllib3.connectionpool:connectionpool.py:206 Starting new HTTP connection (1): 47.97.206.151:3030
DEBUG    urllib3.connectionpool:connectionpool.py:396 http://47.97.206.151:3030 "POST /api-v2/activity/assetExchange/Exchange HTTP/1.1" 200 49
ERROR    root:Log.py:87 [ERROR2020-05-13 12-17-20]断言字符串不在响应体中，断言字符串为:hhhh,响应信息为:"{\"message\":\"兑换失败\",\"code\":1,\"result\":null}"